trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@4
    inputs:
      
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false 

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/webapp/target'
      Contents: '*.war'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'gggg'  
      appName: 'peip'  
      package: '$(Build.ArtifactStagingDirectory)/**/*.war'  
      deploymentMethod: 'auto' 
